- name: Install remi repository
  yum: name=http://rpms.famillecollet.com/enterprise/remi-release-7.rpm state=present 

#- name: Remove repository (and clean up left-over metadata)
#  yum_repository:
#    name: remi
#    state: absent

- name: Install epel repository
  yum: name=https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm state=present

- name: Install webtatic repository
  yum: name=https://mirror.webtatic.com/yum/el7/webtatic-release.rpm state=present

