- name: Set DefaultCharset
  lineinfile: >
    dest=/etc/httpd/conf/httpd.conf
    state=present
    regexp="^AddDefaultCharset"
    line="AddDefaultCharset Off"
  notify: Restart Apache
- name: Set Apache User
  when: webserver_changeowner=="yes"
  lineinfile: >
    dest=/etc/httpd/conf/httpd.conf
    state=present
    regexp="^User"
    line="User {{c5dir_user}}"
  notify: Restart Apache
- name: Set ServerSignature
  lineinfile: >
    dest=/etc/httpd/conf/httpd.conf
    state=present
    regexp="^ServerSignature"
    line="ServerSignature Off"
  notify: Restart Apache
- name: Set ServerTokens
  lineinfile: >
    dest=/etc/httpd/conf/httpd.conf
    state=present
    regexp="^ServerTokens"
    line="ServerTokens Prod"
  notify: Restart Apache
- name: Set HostnameLookups
  lineinfile: >
    dest=/etc/httpd/conf/httpd.conf
    state=present
    regexp="^HostnameLookups"
    line="HostnameLookups Off"
  notify: Restart Apache
- name: Set TraceEnable off
  lineinfile: >
    dest=/etc/httpd/conf/httpd.conf
    state=present
    regexp="^TraceEnable"
    line="TraceEnable Off"
  notify: Restart Apache
# - name: Limit SSL Protocol to non-supporting protocol
#   lineinfile: >
#     dest=/etc/httpd/conf/httpd.conf
#     state=present
#     regexp="^SSLProtocol"
#     line="SSLProtocol All -SSLv2 -SSLv3 -TLSv1 -TLSv1.1"
#   notify: Restart Apache
- name: Add Additional config
  template: src=additional-setting.conf.{{aws_instance_type}}.j2 dest=/etc/httpd/conf.d/additional-setting.conf
  notify: Restart Apache
- name: Change Apache from prefork to event
  lineinfile: >-
    dest='/etc/httpd/conf.modules.d/00-mpm.conf'
    state=present
    backrefs=yes
    regexp='{{ item.regexp }}'
    line='{{ item.line }}'
  with_items:
  - regexp: '^#?\s*LoadModule mpm_prefork_module modules/mod_mpm_prefork.so'
    line: '# LoadModule mpm_prefork_module modules/mod_mpm_prefork.so'
  - regexp: '^#?\s*LoadModule mpm_event_module modules/mod_mpm_event.so'
    line: 'LoadModule mpm_event_module modules/mod_mpm_event.so'
  notify: Restart Apache
